name: Playwright Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout del repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar dependencias
        run: npm ci

      - name: Instalar navegadores Playwright
        run: npx playwright install

      - name: Ejecutar pruebas
        run: npx playwright test --reporter=html

      - name: Subir reporte Playwright
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
